default: &default
  http:
    host: localhost
    port: 4000
  database:
    host: localhost:3306
    username: root
    password: root
    database: ijony_blog
  operators:
    - hi@crazymaple

development:
  <<: *default
  database:
    database: blog

production:
  <<: *default