default: &default
  http:
    host: localhost
    port: 4000
  database:
    host: localhost
    port: 3306
    username: root
    password: root
    database: ijony_blog

development:
  <<: *default

production:
  <<: *default